services:
  postgres:
    image: postgres:latest
    container_name: fastapi-postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PW=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
    ports:
      - "5432:5432"
    volumes:
      - myvolume:/var/lib/postgresql/data


  rabbitmq:
    image: rabbitmq
    ports:
      - 5672:5672
    container_name: fastapi-rabbitmq


  app:
    image: paneas
    depends_on:
      - postgres
      - rabbitmq
    container_name: fastapi-app
    ports:
      - "8000:8000"
    command: >
      bash -c "
        export PYTHONPATH=/app/src:$PYTHONPATH &&
        sleep 5 &&
        poetry run alembic upgrade head &&
        psql -U admin -d main -h postgres -f populate_database.sql &&
        while sleep 1000; do :; done
      "

volumes:
  myvolume:

