services:
  postgres:
    image: postgres:latest
    container_name: fastapi-postgres
    environment:
      - POSTGRES_DB=main
      - POSTGRES_PASSWORD=paneas
      - POSTGRES_USER=admin
    ports:
      - "5432:5432"
    volumes:
      - myvolume:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq
    ports:
      - 5672:5672
    container_name: fastapi-rabbitmq

  app:
    image: paneas
    depends_on:
      - postgres
      - rabbitmq
    container_name: fastapi-app
    volumes:
      - ..:/workspaces:cached
    ports:
      - "8000:8000"
    command: >
      bash -c "
        sleep 5 &&
        poetry run alembic upgrade head &&
        psql -U admin -d main -h postgres -f populate_database.sql &&
        while sleep 1000; do :; done
      "

volumes:
  myvolume: